apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-mongodb-staging-0
  namespace: mongodb-staking-api
spec:
  accessModes:
  - ReadWriteOnce
  dataSource:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: REPLACEME
  resources:
    requests:
      storage: 100Gi
  storageClassName: ebs-sc