name: CI

on:
  push:
    branches:
    - main
    - dev
    tags:
    - '*'

jobs:
  build_lint_test:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.3

    - name: Print Go environment
      run: go env

    - name: Cache Go modules
      id: go-cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.go/pkg/mod
          ~/.cache/go-build
        key: go-mod-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          go-mod-

    - name: Build Staking API Service
      run: make build

    - name: Run tests
      run: make test

  build_docker:
    runs-on: ubuntu-22.04
    needs: build_lint_test
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v6
      with:
        tags: staking-api-service:${{ github.sha }}
        outputs: type=docker,dest=/tmp/staking-api-service.tar
        context: ./
        file: ./contrib/images/staking-api-service

    - name: Upload Docker image to workspace
      uses: actions/upload-artifact@v4
      with:
        name: staking-api-service
        path: /tmp/staking-api-service.tar

  push_docker:
    runs-on: ubuntu-22.04
    needs: build_docker
    steps:
      - name: Download Docker image from workspace
        uses: actions/download-artifact@v4
        with:
          name: staking-api-service
          path: /tmp/

      - name: Load Docker image
        run: docker load -i /tmp/staking-api-service.tar

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker tag staking-api-service:${{ github.sha }} ${{ secrets.DOCKERHUB_REGISTRY_ID }}/staking-api-service:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_REGISTRY_ID }}/staking-api-service:${{ github.sha }}
